# Generated by Django 5.1.1 on 2024-09-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=25)),
                ('training_provider', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
